Address object
NoticeMeDan/map pull request #72
Opened 2018-04-26 13:18 UTC by MrMatten

* OsmReader
  * Changed all Lists and HashMaps to use Vavrs Collections
  * Deleted OSMWay and OSMRelation
  * Made List of AddressObjects

* Address (with help from Emil)
  * Made AddressObject

2018-04-26 13:48 UTC, IMarnild submitted a review, later dismissed

2018-04-27 17:13 UTC, EliasJorgensen requested changes
Ser super nice ud.
Har dog nogle spørgsmål, og nogle ting der muligvis bør ændres, så jeg sætter den som rød for nu.

2018-04-27 17:13 UTC, EliasJorgensen commented on src/main/java/com/noticemedan/map/data/io/OsmReader.java
> +					idToWay.put(Long.parseLong(attributes.getValue("id")), osmWay);
Er ikke sikker på om det her virker, da Vavr's Map er immutable?

2018-04-27 17:13 UTC, EliasJorgensen commented on src/main/java/com/noticemedan/map/data/io/OsmReader.java
> +					OsmNode currentNode;
Er der en grund til at det her variabel bliver deklareret ligemeget udenfor if konteksten?

2018-04-27 17:13 UTC, EliasJorgensen commented on src/main/java/com/noticemedan/map/data/io/OsmReader.java
> +					this.osmWay = osmWay.append(idToNode.get(Long.parseLong(attributes.getValue("ref"))));
Jeg tror vi blev enige om at bruge `.prepend`, da den kører i konstant tid, kontra `.append`s lineære tid.
@Silind @emilbartholdy har det nogen effekt her, om listen er i omvendt rækkefølge?
Et alternativ kunne være at bruge en Vavr queue, som appender/prepender i konstant tid.

2018-04-27 17:13 UTC, EliasJorgensen commented on src/main/java/com/noticemedan/map/data/io/OsmReader.java
> +					this.osmWay = osmWay.append(idToNode.get(Long.parseLong(attributes.getValue("ref"))));
Tror jeg prøver at skrive til Vavr's udviklere her en af dagene, det er totalt åndsvagt at deres List ikke holder styr på tail elementet, så de kan appende i konstant tid. De må have en god grund...

2018-04-27 17:13 UTC, EliasJorgensen commented on src/main/java/com/noticemedan/map/data/io/OsmReader.java
> +		List<Address> addresses = List.empty();
Hvordan kommer de her adresser ud af OsmHandler?

2018-04-28 08:58 UTC, MrMatten commented on src/main/java/com/noticemedan/map/data/io/OsmReader.java
> +					this.osmWay = osmWay.append(idToNode.get(Long.parseLong(attributes.getValue("ref"))));
Prøvede at skifte nogle steder, men så tegnede den helt mærkeligt

2018-04-28 08:59 UTC, MrMatten commented on src/main/java/com/noticemedan/map/data/io/OsmReader.java
> +		List<Address> addresses = List.empty();
Som du har lyst

2018-04-28 09:00 UTC, MrMatten commented on src/main/java/com/noticemedan/map/data/io/OsmReader.java
> +					idToWay.put(Long.parseLong(attributes.getValue("id")), osmWay);
Var også selv i tvivl, men det ser ikke ud som om, der er nogen forskel? Stadig i tvivl om funktionaliteten i idToWay. Jeg kan godt tilføje this.idToWay, hvis det er?

2018-04-28 09:01 UTC, MrMatten commented on src/main/java/com/noticemedan/map/data/io/OsmReader.java
> +					OsmNode currentNode;
Jeg ved ikke hvordan man får det til at være større scope ellers?

2018-04-28 09:01 UTC, EliasJorgensen commented on src/main/java/com/noticemedan/map/data/io/OsmReader.java
> +					idToWay.put(Long.parseLong(attributes.getValue("id")), osmWay);
Prøv at gør det, og se om din unit test så er rød.
Hvis testen er skrevet ordentligt, så bør den faile hvis resultatet ser anderledes ud.

2018-04-28 09:03 UTC, MrMatten commented on src/main/java/com/noticemedan/map/data/io/OsmReader.java
> +					idToWay.put(Long.parseLong(attributes.getValue("id")), osmWay);
Har lige testet, den returnerer void, så det bør virke

2018-04-28 09:03 UTC, EliasJorgensen commented on src/main/java/com/noticemedan/map/data/io/OsmReader.java
> +		List<Address> addresses = List.empty();
Det er op til dig, de skal bare komme ud på en eller anden måde.
Whatever you see fit. :smile:

2018-04-28 09:04 UTC, EliasJorgensen commented on src/main/java/com/noticemedan/map/data/io/OsmReader.java
> +					this.osmWay = osmWay.append(idToNode.get(Long.parseLong(attributes.getValue("ref"))));
Alright. I så fald, så er det fint nok, hvis bare at danmark ikke tager 100 år om at parse.
Som et alternativt alternativ, så kan man prepende hele vejen, og så reverse listen til sidst.
Bør opnå samme effekt som append, bare hurtigere.

2018-04-28 09:06 UTC, EliasJorgensen commented on src/main/java/com/noticemedan/map/data/io/OsmReader.java
> +					OsmNode currentNode;
@MrMatten Hvad med denne her?

2018-04-28 09:11 UTC, MrMatten commented on src/main/java/com/noticemedan/map/data/io/OsmReader.java
> +					this.osmWay = osmWay.append(idToNode.get(Long.parseLong(attributes.getValue("ref"))));
Det er sandt, det kan man godt prøve

2018-04-28 16:23 UTC, emilbartholdy commented on src/main/java/com/noticemedan/map/data/io/OsmReader.java
> +					this.osmWay = osmWay.append(idToNode.get(Long.parseLong(attributes.getValue("ref"))));
Det skal i hvert fald ikke tage længere tid end det gør nu. Det er allerede langsomt nu at performance teste for hele danmark.

2018-04-29 13:07 UTC, EliasJorgensen approved these changes

2018-04-29 13:07 UTC, merged